"""
color_branch.py
===============
Color Branch — Vision Perception Phase (Phase 2, Step 4a of 7)

Operates on the traffic-light ROI produced by roi_crop.py.
Produces traffic-light candidate detections using HSV thresholding and blob
filtering only. No geometry, no neural inference, no temporal filtering.

Purpose
-------
The color branch isolates traffic-light state candidates by color before any
spatial or structural analysis occurs. HSV separates hue from brightness,
making color-based detection more robust than BGR thresholding under the
varied lighting conditions expected on the course. Each color channel (red,
yellow, green) is thresholded independently into a binary mask, and connected
blobs in each mask are filtered by area and aspect ratio to reject background
noise (brake lights, reflections, road markings). Surviving blobs are returned
as candidate detections with bounding boxes and confidence scores for later
fusion with the geometry branch.

Input contract
--------------
  roi : np.ndarray
      Shape  : (H_roi, W_roi, 3)
      Dtype  : uint8
      Color  : BGR
      Source : ROICropResult.traffic_roi from roi_crop.py
               (already preprocessed — undistorted, equalized, blurred)

  hsv_ranges : HSVRanges
      Calibrated thresholds for each traffic light color.
      MISSING DEPENDENCY — must be loaded from calibration/hsv_ranges.json
      generated by the interactive trackbar tuning procedure (Calibration
      Step 2). Do NOT use the placeholder defaults in HSVRanges.__post_init__
      in production. Tuning must be performed under actual course lighting.

  frame_id : int
      Frame counter from the capture loop. Carried into each candidate.

  timestamp_ms : int
      Millisecond timestamp from the capture loop. Carried into each candidate.

  blob_filter : BlobFilter
      Min/max area and aspect ratio bounds for blob acceptance.
      Defaults are starting points only — tune against observed false positive
      rate on actual course hardware.

Output contract
---------------
  Returns : list[TrafficLightCandidate]
      Each element:
          .label       str   — "red" | "yellow" | "green"
          .bbox        tuple — (x, y, w, h) in traffic-light ROI pixel coords
          .confidence  float — in [0.0, 1.0]; see confidence definition below
          .frame_id    int   — from input
          .timestamp_ms int  — from input

  Empty list if no candidates survive blob filtering.
  Coordinates are relative to the traffic-light ROI, not the source frame.
  The caller (feature fusion) is responsible for re-projecting to source
  frame coordinates if needed.

Confidence definition
---------------------
  confidence = clamp( (blob_area - min_area) / (ref_area - min_area), 0.0, 1.0 )

  where ref_area is a per-color reference blob area representing a "full
  signal" detection at expected range. ref_area is a field in BlobFilter.
  This is a normalized area-based heuristic — not a classifier probability.
  It saturates at 1.0 for blobs at or above ref_area.
  Phase 3 temporal filtering and confidence thresholding will consume this.

Failure cases
-------------
  F1 — roi is None or wrong shape/dtype:
       Asserted at entry. Raises ValueError or TypeError.

  F2 — hsv_ranges not provided:
       Raises ValueError with explicit message. Do not fall back to defaults.
       Defaults in HSVRanges exist only for unit-test scaffolding.

  F3 — Red hue wraps around 180°:
       Red in HSV spans [0°-10°] and [170°-180°]. Two masks must be OR-ed.
       This is handled explicitly in _threshold_red(). Omitting the wrap
       causes missed detections on saturated red signals.

  F4 — HSV ranges tuned under wrong lighting:
       cv2.inRange() executes without error but masks will not isolate the
       correct regions. Symptom: all masks empty, or excessive false positives.
       Mitigation: re-tune hsv_ranges under actual course lighting.

  F5 — ROI too small for blob filter min_area:
       All blobs rejected. Returns empty list. Not an error — caller must
       check for empty output and handle it (Phase 3 will see no detections
       for this frame).

  F6 — frame_id or timestamp_ms not supplied:
       Both default to 0. The capture loop is responsible for supplying
       correct values. A consistent 0 will confuse Phase 3 temporal filtering.
"""

import cv2
import numpy as np
import json
import time
from dataclasses import dataclass, field
from typing import List, Optional

# ---------------------------------------------------------------------------
# Configuration dataclasses
# ---------------------------------------------------------------------------

@dataclass
class ColorRange:
    """One HSV color band: lower and upper bounds as (H, S, V) uint8 tuples."""
    lower: tuple   # (H_min, S_min, V_min)
    upper: tuple   # (H_max, S_max, V_max)

@dataclass
class HSVRanges:
    """
    Calibrated HSV thresholds for traffic light color detection.

    MISSING DEPENDENCY in production: load from calibration/hsv_ranges.json
    using load_hsv_ranges(). The placeholder values below are NOT valid for
    any real lighting condition — they are structural scaffolding only.

    Red requires two bands because hue wraps at 180°.
    red_low  covers [0°, ~10°]
    red_high covers [~170°, 180°]
    """
    red_low:  ColorRange = field(default_factory=lambda: ColorRange((0,   100, 100), (10,  255, 255)))
    red_high: ColorRange = field(default_factory=lambda: ColorRange((170, 100, 100), (180, 255, 255)))
    yellow:   ColorRange = field(default_factory=lambda: ColorRange((20,  100, 100), (35,  255, 255)))
    green:    ColorRange = field(default_factory=lambda: ColorRange((40,  100, 100), (80,  255, 255)))

    def __post_init__(self):
        self._validated = False   # flag: True only after load_hsv_ranges() is used

    @property
    def is_calibrated(self) -> bool:
        return self._validated


@dataclass
class BlobFilter:
    """
    Geometric constraints for accepting a blob as a traffic-light candidate.

    min_area      : discard blobs smaller than this (px²) — rejects noise
    max_area      : discard blobs larger than this (px²) — rejects large
                    background regions mistakenly masked
    min_aspect    : w/h lower bound — rejects elongated streaks
    max_aspect    : w/h upper bound — rejects elongated streaks
    ref_area      : blob area (px²) treated as confidence = 1.0 at expected
                    detection range; used in confidence normalization

    Starting defaults below are placeholders.
    Tune against actual course hardware and traffic-light physical dimensions.
    """
    min_area:   float = 50.0
    max_area:   float = 5000.0
    min_aspect: float = 0.3
    max_aspect: float = 3.0
    ref_area:   float = 800.0


# ---------------------------------------------------------------------------
# Output dataclass
# ---------------------------------------------------------------------------

@dataclass
class TrafficLightCandidate:
    label:        str    # "red" | "yellow" | "green"
    bbox:         tuple  # (x, y, w, h) in traffic-light ROI coords
    confidence:   float  # [0.0, 1.0] — area-based heuristic
    frame_id:     int
    timestamp_ms: int


# ---------------------------------------------------------------------------
# Calibration loader
# ---------------------------------------------------------------------------

def load_hsv_ranges(json_path: str) -> HSVRanges:
    """
    Load calibrated HSV thresholds from calibration/hsv_ranges.json.

    Expected JSON structure:
    {
      "red_low":  {"lower": [H, S, V], "upper": [H, S, V]},
      "red_high": {"lower": [H, S, V], "upper": [H, S, V]},
      "yellow":   {"lower": [H, S, V], "upper": [H, S, V]},
      "green":    {"lower": [H, S, V], "upper": [H, S, V]}
    }

    Raises FileNotFoundError if the file does not exist.
    Raises KeyError if any required key is missing.
    """
    with open(json_path, "r") as f:
        data = json.load(f)

    ranges = HSVRanges(
        red_low  = ColorRange(tuple(data["red_low"]["lower"]),  tuple(data["red_low"]["upper"])),
        red_high = ColorRange(tuple(data["red_high"]["lower"]), tuple(data["red_high"]["upper"])),
        yellow   = ColorRange(tuple(data["yellow"]["lower"]),   tuple(data["yellow"]["upper"])),
        green    = ColorRange(tuple(data["green"]["lower"]),    tuple(data["green"]["upper"])),
    )
    ranges._validated = True
    return ranges


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _to_hsv(roi_bgr: np.ndarray) -> np.ndarray:
    """Convert BGR ROI to HSV. No copy of the input is retained."""
    return cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2HSV)


def _threshold_red(hsv: np.ndarray, ranges: HSVRanges) -> np.ndarray:
    """
    Produce red binary mask.
    Red hue wraps: combine low-end [0°–10°] and high-end [170°–180°] bands.
    """
    mask_low  = cv2.inRange(hsv,
                            np.array(ranges.red_low.lower,  dtype=np.uint8),
                            np.array(ranges.red_low.upper,  dtype=np.uint8))
    mask_high = cv2.inRange(hsv,
                            np.array(ranges.red_high.lower, dtype=np.uint8),
                            np.array(ranges.red_high.upper, dtype=np.uint8))
    return cv2.bitwise_or(mask_low, mask_high)


def _threshold_single(hsv: np.ndarray, color_range: ColorRange) -> np.ndarray:
    """Produce binary mask for a single non-wrapping hue range."""
    return cv2.inRange(hsv,
                       np.array(color_range.lower, dtype=np.uint8),
                       np.array(color_range.upper, dtype=np.uint8))


def _clamp(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


def _blobs_to_candidates(
    mask: np.ndarray,
    label: str,
    blob_filter: BlobFilter,
    frame_id: int,
    timestamp_ms: int,
) -> List[TrafficLightCandidate]:
    """
    Extract connected components from a binary mask, apply geometric filters,
    and return surviving blobs as TrafficLightCandidate objects.
    """
    candidates = []

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for contour in contours:
        area = cv2.contourArea(contour)

        # Area filter
        if area < blob_filter.min_area or area > blob_filter.max_area:
            continue

        x, y, w, h = cv2.boundingRect(contour)

        # Aspect ratio filter — guard against zero height
        if h == 0:
            continue
        aspect = w / h
        if aspect < blob_filter.min_aspect or aspect > blob_filter.max_aspect:
            continue

        # Confidence: normalized area relative to reference area
        confidence = _clamp(
            (area - blob_filter.min_area) / max(blob_filter.ref_area - blob_filter.min_area, 1.0),
            0.0, 1.0
        )

        candidates.append(TrafficLightCandidate(
            label        = label,
            bbox         = (x, y, w, h),
            confidence   = round(confidence, 4),
            frame_id     = frame_id,
            timestamp_ms = timestamp_ms,
        ))

    return candidates


# ---------------------------------------------------------------------------
# Core substage
# ---------------------------------------------------------------------------

def extract_traffic_light_candidates(
    roi: np.ndarray,
    hsv_ranges: HSVRanges,
    blob_filter: BlobFilter,
    frame_id: int = 0,
    timestamp_ms: int = 0,
) -> tuple:
    """
    Extract traffic-light color candidates from the traffic-light ROI.

    Parameters
    ----------
    roi          : uint8 BGR ndarray — traffic-light ROI from roi_crop.py
    hsv_ranges   : calibrated HSVRanges — MUST be loaded via load_hsv_ranges()
    blob_filter  : BlobFilter geometric constraints
    frame_id     : integer frame counter from capture loop
    timestamp_ms : millisecond timestamp from capture loop

    Returns
    -------
    (candidates, debug_masks)

    candidates  : list[TrafficLightCandidate]
    debug_masks : dict with keys 'hsv', 'red', 'yellow', 'green'
                  Values are np.ndarray images for debug output.
                  In production, ignore this dict entirely.
    """
    # --- Guard: input validation -------------------------------------------
    if roi is None:
        raise ValueError("extract_traffic_light_candidates: received None ROI")
    if roi.dtype != np.uint8:
        raise TypeError(f"extract_traffic_light_candidates: expected uint8, got {roi.dtype}")
    if roi.ndim != 3 or roi.shape[2] != 3:
        raise ValueError(f"extract_traffic_light_candidates: expected (H,W,3) BGR, got {roi.shape}")
    if hsv_ranges is None:
        raise ValueError(
            "extract_traffic_light_candidates: hsv_ranges is required. "
            "Load from calibration/hsv_ranges.json via load_hsv_ranges(). "
            "Do not pass None or use unvalidated defaults in production."
        )

    # --- Step 1: BGR → HSV --------------------------------------------------
    hsv = _to_hsv(roi)

    # --- Step 2: Per-color thresholding → binary masks ----------------------
    mask_red    = _threshold_red(hsv, hsv_ranges)
    mask_yellow = _threshold_single(hsv, hsv_ranges.yellow)
    mask_green  = _threshold_single(hsv, hsv_ranges.green)

    # --- Step 3: Blob filtering → candidates --------------------------------
    candidates = []
    candidates += _blobs_to_candidates(mask_red,    "red",    blob_filter, frame_id, timestamp_ms)
    candidates += _blobs_to_candidates(mask_yellow, "yellow", blob_filter, frame_id, timestamp_ms)
    candidates += _blobs_to_candidates(mask_green,  "green",  blob_filter, frame_id, timestamp_ms)

    debug_masks = {
        "hsv":    hsv,
        "red":    mask_red,
        "yellow": mask_yellow,
        "green":  mask_green,
    }

    return candidates, debug_masks


# ---------------------------------------------------------------------------
# Debug visualization helper
# ---------------------------------------------------------------------------

_LABEL_COLORS = {
    "red":    (0,   0,   255),
    "yellow": (0,   200, 255),
    "green":  (0,   200,   0),
}

def draw_candidates(roi_bgr: np.ndarray, candidates: List[TrafficLightCandidate]) -> np.ndarray:
    """
    Return a copy of roi_bgr with candidate bounding boxes and labels drawn.
    """
    vis = roi_bgr.copy()
    for c in candidates:
        x, y, w, h = c.bbox
        color = _LABEL_COLORS.get(c.label, (255, 255, 255))
        cv2.rectangle(vis, (x, y), (x + w - 1, y + h - 1), color, 2)
        cv2.putText(vis, f"{c.label} {c.confidence:.2f}",
                    (x, max(y - 4, 10)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1, cv2.LINE_AA)
    return vis


# ---------------------------------------------------------------------------
# Test harness
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    """
    Standalone test harness.

    Input:  traffic-light ROI images from sN/results/  (written by roi_crop.py)
            Specifically looks for files matching *_roi_traffic.png

    If those do not exist, falls back to loading the full image from sN/ and
    applying the traffic-light ROI crop inline (same coordinates as roi_crop.py).

    Output per image → sN/results/  :
      stem_cb_hsv.png          — HSV representation (H channel only, false-color)
      stem_cb_mask_red.png     — red binary mask
      stem_cb_mask_yellow.png  — yellow binary mask
      stem_cb_mask_green.png   — green binary mask
      stem_cb_candidates.png   — ROI with candidate bounding boxes

    MISSING DEPENDENCY: calibration/hsv_ranges.json
      If absent, the harness prints an explicit error and exits.
      Do not attempt to run without calibrated HSV ranges.
    """
    import os
    import sys

    SAMPLE_DIRS = [
        "vision_stack/sample_img/duckietown/s1",
        "vision_stack/sample_img/duckietown/s2",
        "vision_stack/sample_img/duckietown/s3",
        "vision_stack/sample_img/duckietown/s4",
        "vision_stack/sample_img/duckietown/s5",
    ]
    HSV_RANGES_PATH  = "vision_stack/calibration/hsv_ranges.json"
    IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp")

    # --- Load calibrated HSV ranges (hard requirement) ----------------------
    if not os.path.exists(HSV_RANGES_PATH):
        print(
            f"[ERROR] {HSV_RANGES_PATH} not found.\n"
            "HSV range calibration is required before running this substage.\n"
            "Run the interactive trackbar tuning tool under actual course lighting\n"
            "and save the result to calibration/hsv_ranges.json."
        )
        sys.exit(1)

    try:
        hsv_ranges = load_hsv_ranges(HSV_RANGES_PATH)
        print(f"[INFO] HSV ranges loaded from {HSV_RANGES_PATH}")
    except (KeyError, json.JSONDecodeError) as e:
        print(f"[ERROR] Failed to parse {HSV_RANGES_PATH}: {e}")
        sys.exit(1)

    blob_filter = BlobFilter()   # placeholder defaults — tune for production

    total_ok   = 0
    total_fail = 0
    frame_id   = 0

    for sample_dir in SAMPLE_DIRS:
        if not os.path.isdir(sample_dir):
            print(f"[SKIP] Not found: {sample_dir}")
            continue

        results_dir = os.path.join(sample_dir, "results")
        os.makedirs(results_dir, exist_ok=True)

        # Prefer pre-cropped traffic ROIs from roi_crop.py output
        roi_files = sorted(
            f for f in os.listdir(results_dir)
            if f.endswith("_roi_traffic.png")
        ) if os.path.isdir(results_dir) else []

        # Fall back to full images with inline crop
        if not roi_files:
            source_files = sorted(
                f for f in os.listdir(sample_dir)
                if os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
            )
            use_inline_crop = True
        else:
            source_files    = roi_files
            use_inline_crop = False

        if not source_files:
            print(f"[SKIP] No input images in {sample_dir}")
            continue

        for filename in source_files:
            src_path = os.path.join(
                results_dir if not use_inline_crop else sample_dir,
                filename
            )
            stem = filename.replace("_roi_traffic", "")
            stem = os.path.splitext(stem)[0]

            img = cv2.imread(src_path)
            if img is None:
                print(f"[FAIL] Could not read: {src_path}")
                total_fail += 1
                continue

            # Inline crop if pre-cropped ROI not available
            if use_inline_crop:
                H, W = img.shape[:2]
                tl_x = W // 4
                tl_w = W - 2 * (W // 4)
                tl_h = H // 2
                roi = img[0:tl_h, tl_x:tl_x + tl_w]
            else:
                roi = img

            ts_ms = int(time.time() * 1000)

            try:
                candidates, debug_masks = extract_traffic_light_candidates(
                    roi          = roi,
                    hsv_ranges   = hsv_ranges,
                    blob_filter  = blob_filter,
                    frame_id     = frame_id,
                    timestamp_ms = ts_ms,
                )
            except (ValueError, TypeError) as e:
                print(f"[FAIL] {src_path}: {e}")
                total_fail += 1
                continue

            # --- Debug image 1: HSV (H channel only, false-color) -----------
            # Visualize only the H channel rescaled to [0,255] — gives a
            # readable hue map without the full HSV→BGR roundtrip noise.
            h_channel = debug_masks["hsv"][:, :, 0]
            hsv_vis   = cv2.applyColorMap(h_channel, cv2.COLORMAP_HSV)
            cv2.imwrite(os.path.join(results_dir, f"{stem}_cb_hsv.png"), hsv_vis)

            # --- Debug images 2–4: binary masks -----------------------------
            cv2.imwrite(os.path.join(results_dir, f"{stem}_cb_mask_red.png"),    debug_masks["red"])
            cv2.imwrite(os.path.join(results_dir, f"{stem}_cb_mask_yellow.png"), debug_masks["yellow"])
            cv2.imwrite(os.path.join(results_dir, f"{stem}_cb_mask_green.png"),  debug_masks["green"])

            # --- Debug image 5: candidate visualization --------------------
            vis = draw_candidates(roi, candidates)
            cv2.imwrite(os.path.join(results_dir, f"{stem}_cb_candidates.png"), vis)

            label_summary = [f"{c.label}({c.confidence:.2f})" for c in candidates]
            print(
                f"[OK] frame_id={frame_id}  {src_path}  "
                f"candidates={label_summary if label_summary else '[]'}"
            )
            frame_id  += 1
            total_ok  += 1

    print(f"\nDone. {total_ok} processed, {total_fail} failed.")