"""
perspective_transform.py
========================
Perspective Transformation — Vision Perception Phase (Phase 2, Step 6 of 7)

Converts camera-perspective lane detections into bird's-eye (top-down)
coordinates using a pre-calibrated homography matrix. This substage does
nothing but apply the transform. Lateral offset computation is downstream
in Phase 3 state estimation.

Purpose
-------
The camera mounted on the robot sees lane lines in perspective — parallel
lines converge toward a vanishing point. Lateral offset (how far the robot
is from lane center) cannot be computed correctly in perspective space
because equal pixel displacements at different depths represent unequal
real-world distances.

The homography matrix produced by Calibration Step 3 maps a flat-ground
planar region of the camera view to a top-down coordinate frame where:
  - One pixel corresponds to a fixed real-world distance
  - Parallel lane lines appear parallel
  - Lateral displacement is proportional to real-world distance

Two transformation modes are provided:

  MODE A — warp_lane_roi:
      Applies the homography to the entire lane ROI image using
      cv2.warpPerspective(). Produces a bird's-eye BGR image.
      Downstream can extract lane line positions from the warped image
      directly (e.g., find column of white pixels in the warped view).

  MODE B — transform_points:
      Applies the homography to specific (x, y) anchor points extracted
      from lane candidates (e.g., bounding box centroids, contour points).
      Produces transformed (x', y') coordinates in bird's-eye space.
      More efficient than warping the full image when only a few anchor
      points are needed.

Both modes are provided. Phase 3 state estimation will use whichever
representation is most convenient for lateral offset computation.

Input contract
--------------
  For warp_lane_roi:
      lane_roi : np.ndarray
          Shape  : (H_lane, W_lane, 3)
          Dtype  : uint8
          Color  : BGR
          Source : ROICropResult.lane_roi from roi_crop.py
                   (already preprocessed; used as-is for warping)

      homography : HomographyData
          MISSING DEPENDENCY — must be loaded from
          calibration/homography_matrix.npz via load_homography().
          Generated by Calibration Step 3. Do not pass synthetic values.

      output_size : tuple (W_out, H_out)
          Pixel dimensions of the warped output image.
          Must be agreed on when calibration is performed so that the
          destination points used in cv2.getPerspectiveTransform() match
          the output canvas size. Stored inside HomographyData.

  For transform_points:
      points : np.ndarray or list
          Shape  : (N, 2) — array of (x, y) pixel coordinates in the
                   lane ROI coordinate frame (same frame as lane_roi).
          Source : DetectionObject.position centroids from feature_fusion.py,
                   or contour point arrays from geometry_branch.py.
                   Caller decides which points to transform.

      homography : HomographyData
          Same as above.

Output contract
---------------
  warp_lane_roi returns: WarpResult
      .warped_image   np.ndarray (H_out, W_out, 3) uint8 BGR — bird's-eye view
      .homography     HomographyData — passed through for traceability
      .source_shape   tuple (H_lane, W_lane) — input dimensions

  transform_points returns: PointTransformResult
      .transformed_points  np.ndarray (N, 2) float32
                           Each row is (x', y') in bird's-eye pixel coords.
                           Same ordering as input points array.
      .source_points       np.ndarray (N, 2) float32 — input points, preserved
      .homography          HomographyData — passed through

  Coordinate frame of all outputs:
      Origin: top-left of the warped output canvas
      +X:     rightward (same as image convention)
      +Y:     downward (same as image convention)
      Units:  pixels in the warped output frame
      The mapping from warped pixels to real-world metric distances is
      determined by the calibration procedure (known grid dimensions).
      This substage does NOT convert to metres — that is Phase 3's role.

Calibration dependency
----------------------
  calibration/homography_matrix.npz
  Required keys:
      'homography_matrix'  — (3, 3) float64 computed by
                             cv2.getPerspectiveTransform() or
                             cv2.findHomography() during Calibration Step 3
      'output_width'       — int, width of the warped output canvas (px)
      'output_height'      — int, height of the warped output canvas (px)
      'src_points'         — (4, 2) float32, the four source points used
                             when computing the homography (for debug overlay)
      'dst_points'         — (4, 2) float32, the four destination points

  MISSING DEPENDENCY: This file does not exist until Calibration Step 3 is
  performed on the actual course hardware with the actual camera mount.
  Do not substitute a synthetic identity matrix — an identity homography
  leaves the perspective uncorrected and produces wrong lateral offsets.

Failure cases
-------------
  F1 — homography_matrix.npz not found:
       load_homography() raises FileNotFoundError with explicit message.

  F2 — homography computed at wrong camera angle or mount height:
       warpPerspective() executes without error but output is geometrically
       incorrect. Parallel lane lines will not appear parallel in the warped
       image. Mitigation: re-run Calibration Step 3 after any physical camera
       change.

  F3 — points array has wrong shape:
       transform_points() asserts (N, 2). Raises ValueError if shape != 2 cols.

  F4 — points are in source frame coords but homography was built from ROI
       coords (or vice versa):
       Transformed points will be offset by the ROI origin. The caller must
       ensure all input points are in the same coordinate frame as the
       four source points used when computing the homography.

  F5 — output_size mismatch with calibration destination points:
       If output_size passed to warpPerspective differs from the canvas size
       assumed during calibration, the warped image will be cropped or padded
       incorrectly. output_size is stored in HomographyData and must be used
       as-is — do not override it at the call site.

  F6 — lane_roi is None or wrong dtype:
       Asserted at entry. Raises ValueError / TypeError.

  F7 — homography_matrix is not (3, 3):
       Raises ValueError at load time. cv2.warpPerspective requires exactly
       a (3, 3) matrix.
"""

import cv2
import numpy as np
from dataclasses import dataclass
from typing import Optional


# ---------------------------------------------------------------------------
# Calibration container
# ---------------------------------------------------------------------------

@dataclass
class HomographyData:
    """
    Loaded calibration data from calibration/homography_matrix.npz.

    homography_matrix : (3, 3) float64 — the perspective transform
    output_width      : int — warped canvas width in pixels
    output_height     : int — warped canvas height in pixels
    src_points        : (4, 2) float32 — source quad used at calibration time
    dst_points        : (4, 2) float32 — destination quad used at calibration time
    """
    homography_matrix: np.ndarray   # (3, 3) float64
    output_width:      int
    output_height:     int
    src_points:        np.ndarray   # (4, 2) float32
    dst_points:        np.ndarray   # (4, 2) float32


# ---------------------------------------------------------------------------
# Output containers
# ---------------------------------------------------------------------------

@dataclass
class WarpResult:
    warped_image:  np.ndarray    # (H_out, W_out, 3) uint8 BGR
    homography:    HomographyData
    source_shape:  tuple         # (H_lane, W_lane)


@dataclass
class PointTransformResult:
    transformed_points: np.ndarray   # (N, 2) float32 — bird's-eye coords
    source_points:      np.ndarray   # (N, 2) float32 — input, preserved
    homography:         HomographyData


# ---------------------------------------------------------------------------
# Calibration loader
# ---------------------------------------------------------------------------

def load_homography(npz_path: str) -> HomographyData:
    """
    Load homography calibration data from an .npz file.

    Expected keys: 'homography_matrix', 'output_width', 'output_height',
                   'src_points', 'dst_points'

    Raises FileNotFoundError if file is absent.
    Raises KeyError if any required key is missing.
    Raises ValueError if homography_matrix is not (3, 3).

    MISSING DEPENDENCY: calibration/homography_matrix.npz must be generated
    by cv2.getPerspectiveTransform() on actual course hardware before use.
    """
    data = np.load(npz_path)

    H = data["homography_matrix"].astype(np.float64)
    if H.shape != (3, 3):
        raise ValueError(
            f"load_homography: homography_matrix must be (3,3), got {H.shape}. "
            "Re-run Calibration Step 3."
        )

    return HomographyData(
        homography_matrix = H,
        output_width      = int(data["output_width"]),
        output_height     = int(data["output_height"]),
        src_points        = data["src_points"].astype(np.float32),
        dst_points        = data["dst_points"].astype(np.float32),
    )


# ---------------------------------------------------------------------------
# MODE A — warp full lane ROI image
# ---------------------------------------------------------------------------

def warp_lane_roi(
    lane_roi:   np.ndarray,
    homography: HomographyData,
) -> WarpResult:
    """
    Apply homography to the full lane ROI image.

    Produces a bird's-eye BGR image of dimensions
    (homography.output_height, homography.output_width).

    Parameters
    ----------
    lane_roi   : uint8 BGR ndarray (H_lane, W_lane, 3) — from roi_crop.py
    homography : HomographyData — from load_homography()

    Returns
    -------
    WarpResult
    """
    # --- Guard: input validation ------------------------------------------
    if lane_roi is None:
        raise ValueError("warp_lane_roi: lane_roi is None")
    if lane_roi.dtype != np.uint8:
        raise TypeError(f"warp_lane_roi: expected uint8, got {lane_roi.dtype}")
    if lane_roi.ndim != 3 or lane_roi.shape[2] != 3:
        raise ValueError(f"warp_lane_roi: expected (H,W,3) BGR, got {lane_roi.shape}")

    output_size = (homography.output_width, homography.output_height)

    warped = cv2.warpPerspective(
        lane_roi,
        homography.homography_matrix,
        output_size,
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(0, 0, 0),
    )

    return WarpResult(
        warped_image = warped,
        homography   = homography,
        source_shape = lane_roi.shape[:2],
    )


# ---------------------------------------------------------------------------
# MODE B — transform discrete points
# ---------------------------------------------------------------------------

def transform_points(
    points:     np.ndarray,
    homography: HomographyData,
) -> PointTransformResult:
    """
    Apply homography to an array of (x, y) pixel points.

    Parameters
    ----------
    points     : (N, 2) array-like of float or int — (x, y) in lane ROI coords
    homography : HomographyData — from load_homography()

    Returns
    -------
    PointTransformResult
        .transformed_points : (N, 2) float32 in bird's-eye pixel coords
        .source_points      : (N, 2) float32 — input preserved
    """
    pts = np.array(points, dtype=np.float32)

    if pts.ndim != 2 or pts.shape[1] != 2:
        raise ValueError(
            f"transform_points: expected (N, 2) array, got shape {pts.shape}"
        )

    if len(pts) == 0:
        return PointTransformResult(
            transformed_points = pts.copy(),
            source_points      = pts.copy(),
            homography         = homography,
        )

    # cv2.perspectiveTransform requires shape (N, 1, 2)
    pts_reshaped   = pts.reshape(-1, 1, 2)
    transformed    = cv2.perspectiveTransform(pts_reshaped, homography.homography_matrix)
    transformed_2d = transformed.reshape(-1, 2)

    return PointTransformResult(
        transformed_points = transformed_2d,
        source_points      = pts,
        homography         = homography,
    )


# ---------------------------------------------------------------------------
# Debug overlay helpers
# ---------------------------------------------------------------------------

def draw_source_points(image: np.ndarray, homography: HomographyData) -> np.ndarray:
    """
    Draw the four calibration source points on a copy of the input image.
    These are the corners of the ground-plane quad used when computing H.
    """
    vis = image.copy()
    pts = homography.src_points.astype(np.int32)
    cv2.polylines(vis, [pts.reshape(-1, 1, 2)], isClosed=True, color=(0, 255, 255), thickness=2)
    for i, (x, y) in enumerate(pts):
        cv2.circle(vis, (x, y), 5, (0, 200, 255), -1)
        cv2.putText(vis, f"S{i}", (x + 6, y - 4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 200, 255), 1, cv2.LINE_AA)
    return vis


def draw_destination_points(warped: np.ndarray, homography: HomographyData) -> np.ndarray:
    """
    Draw the four calibration destination points on a copy of the warped image.
    """
    vis = warped.copy()
    pts = homography.dst_points.astype(np.int32)
    cv2.polylines(vis, [pts.reshape(-1, 1, 2)], isClosed=True, color=(255, 200, 0), thickness=2)
    for i, (x, y) in enumerate(pts):
        cv2.circle(vis, (x, y), 5, (255, 200, 0), -1)
        cv2.putText(vis, f"D{i}", (x + 6, y - 4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 200, 0), 1, cv2.LINE_AA)
    return vis


def draw_transformed_points(
    warped:   np.ndarray,
    result:   PointTransformResult,
    label:    str = "",
) -> np.ndarray:
    """
    Draw transformed anchor points on a copy of the warped image.
    """
    vis = warped.copy()
    for i, (x, y) in enumerate(result.transformed_points):
        ix, iy = int(round(x)), int(round(y))
        cv2.drawMarker(vis, (ix, iy), (0, 255, 0), cv2.MARKER_CROSS, 12, 2)
        cv2.putText(vis, f"{label}{i}({ix},{iy})", (ix + 5, iy - 5),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.38, (0, 255, 0), 1, cv2.LINE_AA)
    return vis


# ---------------------------------------------------------------------------
# Test harness
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    """
    Standalone test harness.

    MISSING DEPENDENCY check:
      If calibration/homography_matrix.npz does not exist, the harness prints
      an explicit error and exits. Do not proceed without calibrated data.

    Input priority (per sample dir):
      1. Pre-cropped *_roi_lane.png from sN/results/ (written by roi_crop.py)
      2. Falls back to full image from sN/ with inline lane ROI crop

    For each lane ROI:
      MODE A (image warp):
        stem_pt_src_points.png       — source frame with calibration quad overlay
        stem_pt_warped.png           — bird's-eye warped image
        stem_pt_warped_dst_pts.png   — warped image with destination quad overlay

      MODE B (point transform):
        Anchor points are the mid-bottom edge of the lane ROI (a simple proxy
        for lane center at the near edge) plus the four corners. In production
        these would be DetectionObject.position centroids from feature_fusion.py.
        stem_pt_points_warped.png    — warped image with transformed points marked

    All outputs → sN/results/

    Coordinate note printed to stdout for each unique resolution encountered.
    """
    import os
    import sys

    SAMPLE_DIRS = [
        "vision_stack/sample_img/duckietown/s1",
        "vision_stack/sample_img/duckietown/s2",
        "vision_stack/sample_img/duckietown/s3",
        "vision_stack/sample_img/duckietown/s4",
        "vision_stack/sample_img/duckietown/s5",
    ]
    HOMOGRAPHY_PATH  = "vision_stack/calibration/homography_matrix.npz"
    IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp")

    # --- Calibration check --------------------------------------------------
    if not os.path.exists(HOMOGRAPHY_PATH):
        print(
            f"[ERROR] {HOMOGRAPHY_PATH} not found.\n"
            "Homography calibration is required before running this substage.\n"
            "Perform Calibration Step 3 on actual course hardware:\n"
            "  1. Place a flat grid of known dimensions on the course surface.\n"
            "  2. Identify four src/dst point pairs.\n"
            "  3. Compute H with cv2.getPerspectiveTransform().\n"
            "  4. Save to calibration/homography_matrix.npz with keys:\n"
            "     homography_matrix, output_width, output_height,\n"
            "     src_points, dst_points"
        )
        sys.exit(1)

    try:
        homography = load_homography(HOMOGRAPHY_PATH)
        print(
            f"[INFO] Homography loaded from {HOMOGRAPHY_PATH}\n"
            f"       Output canvas: {homography.output_width}x{homography.output_height} px"
        )
    except (KeyError, ValueError) as e:
        print(f"[ERROR] Failed to load homography: {e}")
        sys.exit(1)

    seen_shapes = set()
    total_ok    = 0
    total_fail  = 0

    for sample_dir in SAMPLE_DIRS:
        if not os.path.isdir(sample_dir):
            print(f"[SKIP] Not found: {sample_dir}")
            continue

        results_dir = os.path.join(sample_dir, "results")
        os.makedirs(results_dir, exist_ok=True)

        # Prefer pre-cropped lane ROIs
        lane_files = {}
        if os.path.isdir(results_dir):
            for f in os.listdir(results_dir):
                if f.endswith("_roi_lane.png"):
                    stem = f.replace("_roi_lane.png", "")
                    lane_files[stem] = os.path.join(results_dir, f)

        use_inline = len(lane_files) == 0
        full_imgs = []
        if use_inline:
            full_imgs = sorted(
                f for f in os.listdir(sample_dir)
                if os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
            )
            if not full_imgs:
                print(f"[SKIP] No inputs in {sample_dir}")
                continue
            stems = [os.path.splitext(f)[0] for f in full_imgs]
        else:
            stems = sorted(lane_files)

        for stem in stems:
            if use_inline:
                ext  = next(
                    os.path.splitext(f)[1]
                    for f in full_imgs if os.path.splitext(f)[0] == stem
                )
                img  = cv2.imread(os.path.join(sample_dir, f"{stem}{ext}"))
                if img is None:
                    print(f"[FAIL] Could not read: {stem}")
                    total_fail += 1
                    continue
                H, W    = img.shape[:2]
                lane_roi = img[H // 2 : H, 0 : W]
            else:
                lane_roi = cv2.imread(lane_files[stem])
                if lane_roi is None:
                    print(f"[FAIL] Could not read: {lane_files[stem]}")
                    total_fail += 1
                    continue

            H_r, W_r = lane_roi.shape[:2]

            # Print coordinate context once per unique resolution
            if (H_r, W_r) not in seen_shapes:
                seen_shapes.add((H_r, W_r))
                print(f"\n[COORDS] Lane ROI {W_r}x{H_r}  →  "
                      f"Bird's-eye canvas {homography.output_width}x{homography.output_height}")
                print(f"  src_points: {homography.src_points.tolist()}")
                print(f"  dst_points: {homography.dst_points.tolist()}")

            try:
                # --- MODE A: full image warp --------------------------------
                warp_result = warp_lane_roi(lane_roi, homography)

                src_overlay = draw_source_points(lane_roi, homography)
                cv2.imwrite(
                    os.path.join(results_dir, f"{stem}_pt_src_points.png"),
                    src_overlay)

                cv2.imwrite(
                    os.path.join(results_dir, f"{stem}_pt_warped.png"),
                    warp_result.warped_image)

                dst_overlay = draw_destination_points(warp_result.warped_image, homography)
                cv2.imwrite(
                    os.path.join(results_dir, f"{stem}_pt_warped_dst_pts.png"),
                    dst_overlay)

                # --- MODE B: point transform --------------------------------
                # Proxy anchor points: corners + mid-bottom of lane ROI.
                # In production: use DetectionObject.position centroids.
                proxy_points = np.array([
                    [0,       0      ],   # top-left
                    [W_r - 1, 0      ],   # top-right
                    [W_r - 1, H_r - 1],  # bottom-right
                    [0,       H_r - 1],  # bottom-left
                    [W_r // 2, H_r - 1], # mid-bottom (lane center proxy)
                ], dtype=np.float32)

                pt_result = transform_points(proxy_points, homography)

                pts_overlay = draw_transformed_points(
                    warp_result.warped_image, pt_result, label="P")
                cv2.imwrite(
                    os.path.join(results_dir, f"{stem}_pt_points_warped.png"),
                    pts_overlay)

            except (ValueError, TypeError) as e:
                print(f"[FAIL] {stem}: {e}")
                total_fail += 1
                continue

            print(f"[OK] {stem}  lane_roi={W_r}x{H_r}  "
                  f"warped={homography.output_width}x{homography.output_height}")
            total_ok += 1

    print(f"\nDone. {total_ok} processed, {total_fail} failed.")