"""
preprocess.py
=============
Preprocessing substage — Vision Perception Phase (Phase 2, Step 1 of 7)

Purpose
-------
Conditions the raw BGR frame from Phase 1 before any spatial analysis occurs.
Three sequential operations are applied:

  1. Undistortion   — removes barrel/pincushion lens distortion introduced by
                      the IMX219 optic. Without this, straight lane lines appear
                      curved, and the homography transform (later in Phase 2)
                      will map incorrect world coordinates.

  2. Histogram equalization — redistributes pixel intensity so that features
                      remain visible under varying lighting. Applied per-channel
                      in YCrCb space so that hue and saturation information is
                      preserved for the downstream HSV color branch, and
                      intensity contrast is improved for the Canny/grayscale
                      branch simultaneously.

  3. Gaussian blur  — suppresses high-frequency sensor noise before edge
                      detection and HSV thresholding. Reduces false contours
                      and spurious HSV mask blobs without affecting coarse
                      structural features.

Input contract
--------------
  frame : np.ndarray
      Shape  : (H, W, 3)
      Dtype  : uint8
      Color  : BGR  (OpenCV native, as delivered by cv2.VideoCapture / appsink)
      Source : one frame from the GStreamer ring buffer (Phase 1 output)

  camera_matrix : np.ndarray
      Shape  : (3, 3), dtype float64
      Source : calibration/camera_matrix.npz  key='camera_matrix'
      MISSING DEPENDENCY — must be provided by the caller. This file is
      generated by the camera intrinsic calibration procedure (Step 1 of the
      calibration guide). Do NOT pass a synthetic/identity matrix; the
      undistortion step becomes a no-op and lens distortion is not corrected.

  dist_coeffs : np.ndarray
      Shape  : (1, 5) or (5,), dtype float64
      Source : calibration/camera_matrix.npz  key='dist_coeffs'
      MISSING DEPENDENCY — same file as camera_matrix. Must be the coefficients
      computed by cv2.calibrateCamera() on the actual course hardware.

  gaussian_kernel_size : tuple[int, int]  (default (5, 5))
      Must be odd positive integers. Larger values blur more aggressively.
      Tuned alongside Canny thresholds — if Canny thresholds are re-tuned,
      revisit this value.

  gaussian_sigma : float  (default 0.0)
      When 0.0, OpenCV computes sigma from kernel size automatically.

Output contract
---------------
  Returns : np.ndarray
      Shape  : identical to input (H, W, 3)
      Dtype  : uint8
      Color  : BGR
  The returned array is a new allocation. The input frame is not modified.
  No ROI cropping, no channel splitting, no thresholding is applied here.

Failure cases
-------------
  F1 — camera_matrix / dist_coeffs are None or wrong shape:
       cv2.undistort() will raise or silently produce garbage. Guard with
       an explicit shape assertion before calling.

  F2 — Calibration from wrong hardware or mounting angle:
       undistort() will execute without error but warp the image incorrectly.
       Symptom: lane lines curve in the wrong direction after undistortion.
       Mitigation: re-run intrinsic calibration on actual hardware.

  F3 — gaussian_kernel_size contains an even number:
       cv2.GaussianBlur() raises cv2.error. Enforce odd values at call site.

  F4 — Input frame is not uint8 BGR (e.g. float32 or grayscale):
       YCrCb conversion and equalization will produce incorrect output.
       Assert dtype and channel count at function entry.

  F5 — Input frame is None (dropped frame from appsink):
       Propagates as AttributeError. The caller (Phase 2 loop) must check
       for None before invoking this function.
"""

import cv2
import numpy as np
from typing import Optional

# ---------------------------------------------------------------------------
# Core substage
# ---------------------------------------------------------------------------

def preprocess_frame(
    frame: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    gaussian_kernel_size: tuple = (5, 5),
    gaussian_sigma: float = 0.0,
    undistort_maps: Optional[tuple] = None,
) -> np.ndarray:
    """
    Apply undistortion → histogram equalization → Gaussian blur to one BGR frame.

    Parameters
    ----------
    frame               : uint8 BGR image from Phase 1
    camera_matrix       : (3,3) float64 — from calibration/camera_matrix.npz
    dist_coeffs         : (1,5) or (5,) float64 — from calibration/camera_matrix.npz
    gaussian_kernel_size: odd (w, h) tuple for GaussianBlur
    gaussian_sigma      : sigma for GaussianBlur (0 = auto from kernel size)

    Returns
    -------
    np.ndarray : preprocessed uint8 BGR frame, same spatial dimensions as input
    """
    # --- Guard: input validation -------------------------------------------
    if frame is None:
        raise ValueError("preprocess_frame: received None frame (dropped by appsink?)")
    if frame.dtype != np.uint8:
        raise TypeError(f"preprocess_frame: expected uint8, got {frame.dtype}")
    if frame.ndim != 3 or frame.shape[2] != 3:
        raise ValueError(f"preprocess_frame: expected (H,W,3) BGR, got shape {frame.shape}")
    if camera_matrix is None or dist_coeffs is None:
        raise ValueError(
            "preprocess_frame: camera_matrix and dist_coeffs are required. "
            "Run intrinsic calibration and load calibration/camera_matrix.npz."
        )
    if camera_matrix.shape != (3, 3):
        raise ValueError(f"preprocess_frame: camera_matrix must be (3,3), got {camera_matrix.shape}")
    kw, kh = gaussian_kernel_size
    if kw % 2 == 0 or kh % 2 == 0:
        raise ValueError(f"preprocess_frame: gaussian_kernel_size must be odd, got {gaussian_kernel_size}")

    # --- Step 1: Undistortion -----------------------------------------------
    # cv2.undistort allocates a new output buffer; input frame is not modified.
    if undistort_maps is not None:
        map1, map2 = undistort_maps
        undistorted = cv2.remap(frame, map1, map2, interpolation=cv2.INTER_LINEAR)
    else:
        undistorted = cv2.undistort(frame, camera_matrix, dist_coeffs)

    # --- Step 2: Histogram equalization (YCrCb, Y channel only) -------------
    # Convert to YCrCb so equalization acts only on luma (Y).
    # Cr and Cb carry the color information used by the HSV branch downstream.
    # Equalizing in BGR directly would shift hue/saturation arbitrarily.
    ycrcb = cv2.cvtColor(undistorted, cv2.COLOR_BGR2YCrCb)
    ycrcb[:, :, 0] = cv2.equalizeHist(ycrcb[:, :, 0])   # in-place on Y channel
    equalized = cv2.cvtColor(ycrcb, cv2.COLOR_YCrCb2BGR)

    # --- Step 3: Gaussian blur ----------------------------------------------
    blurred = cv2.GaussianBlur(equalized, gaussian_kernel_size, gaussian_sigma)

    return blurred


# ---------------------------------------------------------------------------
# Calibration loader helper
# ---------------------------------------------------------------------------

def load_calibration(npz_path: str) -> tuple:
    """
    Load camera_matrix and dist_coeffs from a .npz file saved by calibrateCamera().

    Expected keys: 'camera_matrix', 'dist_coeffs'

    Returns (camera_matrix, dist_coeffs) as float64 arrays.
    Raises FileNotFoundError or KeyError if the file or keys are missing.

    MISSING DEPENDENCY: the .npz file must exist at npz_path before this runs.
    """
    data = np.load(npz_path)
    camera_matrix = data["camera_matrix"].astype(np.float64)
    dist_coeffs   = data["dist_coeffs"].astype(np.float64)
    return camera_matrix, dist_coeffs

def build_undistort_maps(
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    image_size: tuple,          # (W, H)
) -> tuple:
    """
    Precompute undistortion maps for cv2.remap.
    Call once at startup, reuse every frame.
    Returns (map1, map2) — pass both to remap_undistort().
    """
    new_camera_matrix, _ = cv2.getOptimalNewCameraMatrix(
        camera_matrix, dist_coeffs, image_size, alpha=1
    )
    map1, map2 = cv2.initUndistortRectifyMap(
        camera_matrix, dist_coeffs, None,
        new_camera_matrix, image_size, cv2.CV_16SC2
    )
    return map1, map2


# ---------------------------------------------------------------------------
# Test harness
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    """
    Standalone test harness.

    Loads every .jpg / .png from each of the five sample image directories,
    runs preprocess_frame(), and writes four debug images per input into
    vision_stack/sample_img/duckietown/sN/results/

    MISSING DEPENDENCY: calibration/camera_matrix.npz must exist before
    running. If it does not exist, the harness falls back to running Steps 2
    and 3 only (equalization + blur) and prints a warning. This fallback is
    for development convenience only — undistortion is required in production.

    Directory structure:
        vision_stack/sample_img/duckietown/s1/
        vision_stack/sample_img/duckietown/s2/
        vision_stack/sample_img/duckietown/s3/
        vision_stack/sample_img/duckietown/s4/
        vision_stack/sample_img/duckietown/s5/
    """
    import os
    import sys

    SAMPLE_DIRS = [
        "vision_stack/sample_img/duckietown/s1",
        "vision_stack/sample_img/duckietown/s2",
        "vision_stack/sample_img/duckietown/s3",
        "vision_stack/sample_img/duckietown/s4",
        "vision_stack/sample_img/duckietown/s5",
    ]
    CALIBRATION_PATH = "vision_stack/calibration/camera_matrix.npz"
    GAUSSIAN_KERNEL  = (5, 5)
    GAUSSIAN_SIGMA   = 0.0
    IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp")

    # --- Load calibration (or warn and skip undistortion) -------------------
    camera_matrix = None
    dist_coeffs   = None
    skip_undistort = False

    if os.path.exists(CALIBRATION_PATH):
        try:
            camera_matrix, dist_coeffs = load_calibration(CALIBRATION_PATH)
            print(f"[INFO] Calibration loaded from {CALIBRATION_PATH}")
        except KeyError as e:
            print(f"[ERROR] Calibration file missing expected key: {e}")
            sys.exit(1)
    else:
        print(
            f"[WARNING] {CALIBRATION_PATH} not found. "
            "Undistortion will be SKIPPED. "
            "Run intrinsic calibration before production use."
        )
        skip_undistort = True

    # --- Process each sample directory --------------------------------------
    total_processed = 0
    total_failed    = 0

    for sample_dir in SAMPLE_DIRS:
        if not os.path.isdir(sample_dir):
            print(f"[SKIP] Directory not found: {sample_dir}")
            continue

        results_dir = os.path.join(sample_dir, "results")
        os.makedirs(results_dir, exist_ok=True)

        image_files = sorted(
            f for f in os.listdir(sample_dir)
            if os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
        )

        if not image_files:
            print(f"[SKIP] No images found in {sample_dir}")
            continue

        for filename in image_files:
            img_path = os.path.join(sample_dir, filename)
            stem     = os.path.splitext(filename)[0]

            # Load
            original = cv2.imread(img_path)
            if original is None:
                print(f"[FAIL] Could not read: {img_path}")
                total_failed += 1
                continue

            # --- Debug image 1: original ------------------------------------
            cv2.imwrite(os.path.join(results_dir, f"{stem}_1_original.png"), original)

            # --- Step 1: Undistortion (or passthrough if no calibration) ----
            if skip_undistort:
                undistorted = original.copy()
            else:
                undistorted = cv2.undistort(original, camera_matrix, dist_coeffs)

            # --- Debug image 2: undistorted ---------------------------------
            cv2.imwrite(os.path.join(results_dir, f"{stem}_2_undistorted.png"), undistorted)

            # --- Step 2: Histogram equalization -----------------------------
            ycrcb = cv2.cvtColor(undistorted, cv2.COLOR_BGR2YCrCb)
            ycrcb[:, :, 0] = cv2.equalizeHist(ycrcb[:, :, 0])
            equalized = cv2.cvtColor(ycrcb, cv2.COLOR_YCrCb2BGR)

            # --- Debug image 3: equalized -----------------------------------
            cv2.imwrite(os.path.join(results_dir, f"{stem}_3_equalized.png"), equalized)

            # --- Step 3: Gaussian blur --------------------------------------
            blurred = cv2.GaussianBlur(equalized, GAUSSIAN_KERNEL, GAUSSIAN_SIGMA)

            # --- Debug image 4: blurred (final output) ----------------------
            cv2.imwrite(os.path.join(results_dir, f"{stem}_4_blurred.png"), blurred)

            print(f"[OK] {img_path}  →  {results_dir}/{stem}_*.png")
            total_processed += 1

    print(f"\nDone. {total_processed} processed, {total_failed} failed.")
    if skip_undistort:
        print("REMINDER: undistortion was skipped. Provide calibration/camera_matrix.npz for full output.")